### ISSUE TITLE
Suggestions for Maintainability

### ISSUE THREAD

**Issue by the-Jamz** [alexxroche/e2#4]
I suppose this isn't really the primary reason behind you asking for someone to take a look so I'll compress all these thoughts to here, but Rust has a relatively clear standard of how to write idiomatically.

The steps to follow this (mostly) are:
- `cargo fmt` (automatically format code)
- `cargo clippy` (which reveals a bunch of annoying suggestions but help clean up code)

Aside from this, there is a section in the rust book on how to write [comments](https://doc.rust-lang.org/book/ch03-04-comments.html), and this chapter in general is quite a good read.

**Comment by alexxroche** [comment]
It seems that clippy has improved since I last ran it. (Thanks for the pointer.) 
`fmt` only changed one of my tests. (I do have a few exceptions to fmt in the code, but that makes it fit better in my IDE.)

**Comment by alexxroche** [comment]
I've tested those cosmetic changes, and the compiled binary performs exactly the same. (But I agree that `clippy` and `fmt` do help with maintainability.)
